<h3 style="color: blueviolet; font-weight: bold;"> Bintang Ilham Syahputra</h3>
<p><b>SI-UI 2016</b></p>
<hr>
<br>
<img src="https://pbs.twimg.com/profile_images/1226662546637127682/AVAo7GDr.jpg"/>
<p>Bintang Ilham Sy merupakan lulusan sistem informasi UI tahun 2020. Saat ini, dia masih menganggur.
    Disela kesibukannya sebagai pengangguran, dia tetap produktif dengan memainkan mobile legend. Skin yang digunakan adalah Hanabi.
    Namun sayang, dia masih di level <b>Elite.</b> Mabar Skuy !!!!!.
</p>
