<script src="https://kit.fontawesome.com/yourcode.js"></script>
<h3>Anda dapat menghubungi memfollow saya (jika ingin dan tidak ada paksaan) di link berikut:</h3>
<br>
<hr>
<br>
<p><i class='fab fa-instagram' style='font-size:36px'></i> : bintangilha41</p>
<p><i class='fab fa-linkedin' style='font-size:36px'></i> : Bintang Ilham Syahputra</p>
<p><i class='fab fa-twitter' style='font-size:36px'></i> : BintangIlhamSy3</p>
